# Generated by Django 5.0 on 2025-04-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='states',
        ),
    ]
