# Generated by Django 5.0 on 2025-05-01 10:14

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_carrier_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbreviation', models.CharField(blank=True, max_length=200, null=True)),
                ('security_groups', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('administrator', 'Administrator'), ('agent_gem', 'Agent GEM'), ('agent_statements', 'Agent Statements'), ('commission_staff', 'Commission Staff')], max_length=57, null=True)),
                ('carrier_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'InActive')], max_length=100, null=True)),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_details', to='main.carrier')),
            ],
        ),
    ]
