# Generated by Django 5.0 on 2025-05-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carrierdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrierdetails',
            old_name='Abbreviation',
            new_name='abbreviation',
        ),
    ]
