# Generated by Django 5.0 on 2025-05-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_address_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='CarrierAddress',
        ),
        migrations.RenameModel(
            old_name='Phone',
            new_name='CarrierPhone',
        ),
    ]
