# Generated by Django 5.0 on 2025-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_address_carrieraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieraddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
