# Generated by Django 5.0 on 2025-05-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_carrieraddress_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('follow_up_user', models.CharField(max_length=100)),
                ('follow_up_team', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('activity_date', models.DateField()),
                ('priority', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='carrier_activity_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carrier')),
            ],
        ),
    ]
