# Generated by Django 5.0 on 2025-05-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carriernotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieractivity',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrieractivity', to='main.carrier'),
        ),
        migrations.AlterField(
            model_name='carriernotes',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriernotes', to='main.carrier'),
        ),
        migrations.CreateModel(
            name='CarrierFormName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('form_number', models.CharField(blank=True, max_length=100)),
                ('coverage_type', models.CharField(blank=True, max_length=100)),
                ('form_file', models.FileField(blank=True, null=True, upload_to='carrier_notes_attachments/')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrierformname', to='main.carrier')),
            ],
        ),
    ]
