# Generated by Django 5.1 on 2025-05-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_carrieractivity_carrier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('Medical', 'Medical'), ('Dental', 'Dental'), ('Vision', 'Vision')], max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefit_summary', models.FileField(blank=True, null=True, upload_to='product_files/')),
                ('plan_grid', models.FileField(blank=True, null=True, upload_to='product_files/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='product_files/')),
                ('states', models.JSONField(blank=True, default=list)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.carrier')),
            ],
        ),
    ]
