# Generated by Django 5.1 on 2025-05-02 09:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carrierproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierproduct',
            name='states',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas')], max_length=31, null=True),
        ),
    ]
