# Generated by Django 5.1 on 2025-05-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_carrierproduct_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carrier')),
            ],
        ),
    ]
