# Generated by Django 5.1 on 2025-05-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_carrierwebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierwebsite',
            name='websites',
        ),
        migrations.AddField(
            model_name='carrierwebsite',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='main.carrier'),
            preserve_default=False,
        ),
    ]
