# Generated by Django 5.0 on 2025-05-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_carrierwebsite_websites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('ext', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Other', 'Other')], max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_addresses', to='main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_detail', to='main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_phones', to='main.agency')),
            ],
        ),
    ]
