# Generated by Django 5.0 on 2025-05-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_agency_agencyaddress_agencydetails_agencyphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
