# Generated by Django 5.0 on 2025-05-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_agency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_note', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agency_notes_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencynotes', to='main.agency')),
            ],
        ),
    ]
