# Generated by Django 5.1 on 2025-05-23 07:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_agencynotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('business_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('npn', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_agency', to='main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_note', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_team', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.BooleanField(default=False)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agent_activity_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_activity', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('other_lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_market', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('administrator', 'Administrator'), ('agent_gem', 'Agent GEM'), ('agent_statements', 'Agent Statements'), ('commission_staff', 'Commission Staff')], max_length=57, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('team', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Team 1', 'Team 1'), ('Team 2', 'Team 2'), ('Your Sales Pipeline Team', 'Your Sales Pipeline Team')], max_length=38, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('key_agent', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_detail', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_EO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eo_required', models.BooleanField(default=False)),
                ('eo_expiration_date', models.DateField(blank=True, null=True)),
                ('eo_attachment', models.FileField(blank=True, null=True, upload_to='agent_eo_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_eo', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('resident_state', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('license_file', models.FileField(blank=True, null=True, upload_to='agent_license_file/')),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_license', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('children_names', models.TextField(blank=True, null=True)),
                ('incentives', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_personal', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_note', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agent_notes_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_notes', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Agents_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_status', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_file', models.FileField(blank=True, null=True, upload_to='agent_contract_file/')),
                ('direct_paid_by_carrier', models.BooleanField(default=False)),
                ('agent_number1', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_number2', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_number3', models.CharField(blank=True, max_length=100, null=True)),
                ('medicare_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('certified_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_contract', to='main.agent')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carrier')),
            ],
        ),
    ]
