# Generated by Django 5.1 on 2025-05-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_agent_agent_activity_agent_details_agent_eo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Other', 'Other')], max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_addresses', to='main.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_phones', to='main.agent')),
            ],
        ),
    ]
