# Generated by Django 5.1 on 2025-05-23 11:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_agentaddress_agentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_details',
            name='primary_market',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Med Supp', 'Med Supp'), ('Health', 'Health'), ('Life', 'Life'), ('P&C', 'P&C')], max_length=24, null=True),
        ),
    ]
