# Generated by Django 5.1 on 2025-05-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_agent_details_primary_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAgencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_agencies', to='main.agent')),
            ],
        ),
    ]
