# Generated by Django 5.1 on 2025-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_agentagencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
