# Generated by Django 5.0 on 2025-05-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_agency_business_phone_alter_agencyphone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('individual_type', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('business_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('home_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('servicing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agent')),
            ],
        ),
    ]
