# Generated by Django 5.0 on 2025-05-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_individuals'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_team', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.BooleanField(default=False)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='individual_activity_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_activity', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Other', 'Other')], max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_addresses', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=100, null=True)),
                ('descresed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('mbi', models.CharField(blank=True, max_length=100, null=True)),
                ('medicare_eddective_date_A', models.DateField(blank=True, null=True)),
                ('medicare_eddective_date_B', models.DateField(blank=True, null=True)),
                ('smoker_status', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('other_lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_agent', to='main.agent')),
                ('affiliate_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_agent', to='main.agent')),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_detail', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_note', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='individual_notes_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_notes', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_phones', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('correspondence', models.CharField(max_length=100)),
                ('correspondence_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('correspondence_notes', models.TextField(blank=True, null=True)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_relationship', to='main.individuals')),
            ],
        ),
    ]
