# Generated by Django 5.0 on 2025-05-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_individualactivity_individualaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualdetails',
            old_name='medicare_eddective_date_A',
            new_name='medicare_effective_date_A',
        ),
        migrations.RenameField(
            model_name='individualdetails',
            old_name='medicare_eddective_date_B',
            new_name='medicare_effective_date_B',
        ),
    ]
