# Generated by Django 5.0 on 2025-05-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_medicare_eddective_date_a_individualdetails_medicare_effective_date_a_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualPhone',
        ),
    ]
