# Generated by Django 5.0 on 2025-05-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_individualphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuals',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carrier'),
        ),
    ]
