# Generated by Django 5.0 on 2025-05-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_individuals_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('smoker_status', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_relationship_basic_info', to='main.individuals')),
            ],
        ),
    ]
