# Generated by Django 5.0 on 2025-05-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_relationshipbasicinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshipbasicinfo',
            name='individual_name',
        ),
    ]
