# Generated by Django 5.0 on 2025-05-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_relationshipbasicinfo_individual_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipbasicinfo',
            name='individual_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='individual_relationship_basic_info', to='main.individuals'),
            preserve_default=False,
        ),
    ]
