# Generated by Django 5.0 on 2025-05-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_relationshipbasicinfo_individual_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshipbasicinfo',
            name='individual_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_relationship_basic_info', to='main.individuals'),
        ),
    ]
