# Generated by Django 5.1 on 2025-06-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_relationshipbasicinfo_individual_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('coverage_type', models.CharField(max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_agent', to='main.agent')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_carrier', to='main.carrier')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_individual', to='main.individuals')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_team', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.BooleanField(default=False)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='policy_activity_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_activity', to='main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.FloatField(blank=True, null=True)),
                ('pay_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('lives', models.IntegerField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('aoo_submit_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('term_date', models.DateField(blank=True, null=True)),
                ('pay_method', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=100, null=True)),
                ('election', models.CharField(blank=True, max_length=100, null=True)),
                ('election_notes', models.TextField(blank=True, null=True)),
                ('additional_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_additional_agent', to='main.agent')),
                ('policy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_details', to='main.policy')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_by_agent', to='main.agent')),
                ('who_is_covered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_is_covered', to='main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_note', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='policy_notes_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_notes', to='main.policy')),
            ],
        ),
    ]
