# Generated by Django 5.0 on 2025-06-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_policy_policyactivity_policydetails_policynotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policydetails',
            old_name='aoo_submit_date',
            new_name='app_submit_date',
        ),
    ]
