# Generated by Django 5.0 on 2025-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_aoo_submit_date_policydetails_app_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydetails',
            name='who_is_covered',
            field=models.BooleanField(default=False),
        ),
    ]
