# Generated by Django 5.0 on 2025-06-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_policydetails_who_is_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierproduct',
            name='coverage_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('coverage_effective_date', models.DateField(blank=True, null=True)),
                ('coverage_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_renewal_date', models.DateField(blank=True, null=True)),
                ('coverage_renewal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_lives', models.IntegerField(blank=True, null=True)),
                ('coverage_termination_policy', models.CharField(blank=True, max_length=255)),
                ('coinsurance', models.CharField(blank=True, max_length=50)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductible_family', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_out_of_pocket', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_out_of_pocket_family', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('out_of_network_costs', models.TextField(blank=True)),
                ('annual_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lifetime_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rx_tier1', models.CharField(blank=True, max_length=255)),
                ('rx_tier2', models.CharField(blank=True, max_length=255)),
                ('rx_tier3', models.CharField(blank=True, max_length=255)),
                ('rx_tier4', models.CharField(blank=True, max_length=255)),
                ('rx_tier5', models.CharField(blank=True, max_length=255)),
                ('single_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plus_spouse_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plus_children_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('family_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pharmacy_network', models.CharField(blank=True, max_length=255)),
                ('provider_network', models.CharField(blank=True, max_length=255)),
                ('coverage_notes', models.TextField(blank=True)),
                ('fees', models.TextField(blank=True)),
                ('carrier_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carrierproduct')),
                ('policy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_coverage', to='main.policy')),
            ],
        ),
    ]
