# Generated by Django 5.0 on 2025-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_carrierproduct_coverage_type_policycoverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycoverage',
            name='coverage_lives',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='lives',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='premium',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
