# Generated by Django 5.1 on 2025-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_policycoverage_coverage_lives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriernotes',
            name='pin_note',
            field=models.BooleanField(default=False),
        ),
    ]
