# Generated by Django 5.1 on 2025-06-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_carrieractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('refill_frequency', models.CharField(max_length=100)),
                ('generic', models.CharField(max_length=100)),
                ('individual_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_prescription', to='main.individuals')),
            ],
        ),
    ]
