# Generated by Django 5.1 on 2025-06-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='individual_name',
        ),
    ]
