# Generated by Django 5.1 on 2025-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_prescription_individual_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='zipcode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
