# Generated by Django 5.1 on 2025-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_prescription_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_activity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualactivity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyactivity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
