# Generated by Django 5.1 on 2025-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_agent_activity_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_activity',
            name='pin_note',
        ),
    ]
