# Generated by Django 5.1 on 2025-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_prescription_ndc'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='actual_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='display_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
