# Generated by Django 5.0 on 2025-06-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_prescription_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='individual_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='individual_prescription', to='main.individuals'),
            preserve_default=False,
        ),
    ]
